<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Chatbot Query History - Track all queries for analytics
        Schema::create('chatbot_queries', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->onDelete('cascade');
            $table->text('original_query'); // User's original query
            $table->text('translated_query')->nullable(); // Translated/English version
            $table->enum('query_type', ['general', 'time_based', 'statistical', 'simple', 'complex', 'unknown'])->default('unknown');
            $table->text('generated_sql')->nullable(); // SQL generated by AI
            $table->boolean('sql_executed')->default(false); // Whether SQL ran successfully
            $table->integer('result_count')->nullable(); // Number of results returned
            $table->integer('execution_time_ms')->nullable(); // Execution time in milliseconds
            $table->string('model_used')->nullable(); // AI model used (e.g., "Primary Llama")
            $table->boolean('was_successful')->default(false); // Overall success
            $table->text('error_message')->nullable(); // Error if any
            $table->timestamps();
            
            $table->index(['user_id', 'created_at']);
            $table->index(['query_type', 'was_successful']);
        });

        // Chatbot Feedback - User feedback on responses
        Schema::create('chatbot_feedback', function (Blueprint $table) {
            $table->id();
            $table->foreignId('chatbot_query_id')->constrained('chatbot_queries')->onDelete('cascade');
            $table->foreignId('user_id')->constrained('users')->onDelete('cascade');
            $table->enum('rating', ['helpful', 'not_helpful', 'partially_helpful']);
            $table->text('comment')->nullable(); // Optional user comment
            $table->timestamps();
            
            $table->index('chatbot_query_id');
            $table->index(['rating', 'created_at']);
        });

        // Chatbot Accuracy Metrics - Aggregate accuracy stats
        Schema::create('chatbot_accuracy_metrics', function (Blueprint $table) {
            $table->id();
            $table->date('metric_date'); // Date of metrics
            $table->integer('total_queries')->default(0);
            $table->integer('successful_queries')->default(0);
            $table->integer('failed_queries')->default(0);
            $table->decimal('success_rate', 5, 2)->default(0); // Percentage
            $table->integer('avg_response_time_ms')->default(0);
            $table->integer('helpful_feedback')->default(0);
            $table->integer('not_helpful_feedback')->default(0);
            $table->decimal('satisfaction_rate', 5, 2)->default(0); // Percentage
            $table->timestamps();
            
            $table->unique('metric_date');
            $table->index('metric_date');
        });

        // Chatbot Fallback Responses - Pre-defined responses when AI fails
        Schema::create('chatbot_fallback_responses', function (Blueprint $table) {
            $table->id();
            $table->string('trigger_keyword'); // Keyword that triggers this response
            $table->text('response_text'); // The fallback response
            $table->integer('usage_count')->default(0); // How many times used
            $table->boolean('is_active')->default(true);
            $table->timestamps();
            
            $table->index('trigger_keyword');
            $table->index('is_active');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('chatbot_fallback_responses');
        Schema::dropIfExists('chatbot_accuracy_metrics');
        Schema::dropIfExists('chatbot_feedback');
        Schema::dropIfExists('chatbot_queries');
    }
};
